name: section2_flutter
description: Section 2 coding tasks with separated files
publish_to: 'none'
environment:
  sdk: '>=3.0.0 <4.0.0'

version: 1.0.0+1

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.0

flutter:
  uses-material-design: true
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
#  aem_exam: any
